# Generated by Django 2.0.6 on 2018-07-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('password', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True)),
                ('points', models.TextField(blank=True)),
                ('email', models.TextField(blank=True)),
                ('badges', models.TextField(blank=True)),
            ],
        ),
    ]
