# Generated by Django 2.0.6 on 2018-07-25 23:32

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180725_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.TextField(blank=True)),
                ('answer', models.TextField(blank=True)),
                ('votes', models.IntegerField(blank=True)),
                ('createdOn', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.TextField(blank=True)),
                ('question', models.TextField(blank=True)),
                ('createdOn', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('tags', models.TextField(blank=True)),
                ('answers', models.ManyToManyField(to='users.Answer')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
