# Generated by Django 2.0.6 on 2018-07-26 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180726_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='questionId',
        ),
        migrations.AddField(
            model_name='question',
            name='tag',
            field=models.ManyToManyField(to='users.Tag'),
        ),
    ]
