version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/travqserv/
hooks:
  BeforeInstall:
    - location: scripts/stop_gunicorn
      timeout: 300
      runas: root
    - location: scripts/copy_db
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/revert_db
      timeout: 300
      runas: root
    - location: scripts/start_gunicorn
      timeout: 300
      runas: root
